apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: basic-auth
  namespace: default
spec:
  encryptedData:
    password: AgAi+/P3NdSzaVGMtdolq20ETwKXv5oEAG2TtBl0NgXdivT1rpw18ve2u6PftFQIsa+WIPIjy2xKqsBT6sJBE4xUzUwzvf4+VQW8+hnPhMvWfQLXa2/dchAQ2Ndx0kmFsN1mntztTPtrFhaC1/EAWRzTMrJZr1mLlFn+QinRMhbi9b4N/NyYQWMnH9CZo001w+bJhZ/ZUaa/g5axFiuKpTYlfgdTWn80OgEEALvb7icsGE+B+zc5kGJiPH+M5rGBYwb+ozIZS3O4WW3Z8XS0a4jK5Im5fd0PW5iMMgYdOhlRxX42/LlAjdwOWWtQkoPBH2PNF6Mr0oMFVw0Cvm4veexLpYNlr7xE2bmieLtjZXox9s/JGXVT7hvmb3JqXhxGxVJCAd359yMD55XFd3bNdiDErDcKsgDWMzRWLePkP5bLia1YWhCNZhKDy2IQ6tNqNqZZjVKRyKvrw9Ed2PgZMDocMfVRvOQw8MHRc+g3YWOy6alrNnIguM++cfQ7uyBltzFF7e1e+6wWzcym46Q1UwMb5rskzsZ/NcXTITtrSAk4SfHUWgXe+KyEfTBWV8CPYjEGlUmMPcK6ya7xaCe/85GyQKJA8aYGZL+k1X4c9Ynfsf9/0iezZKQMUNtTCNXxaCEtoxCDJEKt46jI1vldf5Xdwe0KPjFA7Ur0bbJmN/HMF0nFYEZxdvMEyN/HnffsHIZHM/yXZfvzdg==
    user: AgBr7phka/lVltEOISVIqvOFdsHWxqR7lyGAm8dH/tOQbgbOd5hC7WtkxobZ/3fzofEOHXCkwYOzvoK6/u3RRQqLL224IXU0LnUownP0RJtTatGdz9W67dd8Z4dBmTpIlpcitLICKr98k4otz3hOcKbeARx9S/4ipN5ZTKaGS79CfQkhrlqsDWWyGLqEmDP2hdfesalfhCgVuW5M3k+86i5F9Su4h+bb0JAWqHk1T6O5uiWl4ngzbL1RziVZRvO9AzhzSCmqiPKKRC8kvvpXeapWLN08Du8e/+e0i+qWtJ7va60hjyeFlj85k34u4tHL5B43zigOQQzljNNOYczcjZXTuq4DCT6TQz2xiV/imelVxRfUpJeUb4HcHkUx019SoyXMRB39LoDp2diVVRGVBMlv9TYtWjZKValnYeAFlErtdbn1jRrT82b3n712gaDaaqDGcgj4Qd3Nfx3QzU6GOAy4or5q6DiZ3u5wxGocvs+hp0gjWP8uipLUiK7w1bcXJdjdAsKg9rIFeYJKS6gEH90NBLAXF6kKq7WFdSiNK8JEwEcC03rEVzagzGEmYXoypyPXtVeLC4GWiTilO9J37j7RuZw2TSj02f5CHeQiUQNRvtQHYhirMWfscwXrZrOdYSw4flgci716yuSWElEzB+wRCPGaLSQa3kiUy7znTd0pAlM1/GLl3XIfoYcvVxFl4273ajw68A==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: basic-auth
      namespace: default

