apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: basic-auth
  namespace: default
spec:
  encryptedData:
    password: AgBo4Q+Pq50MIsy5FJNJ3Xw+YzGuk+ZCnETk4zw0Kr6So4FCoBPKZZxW36ipEpYQOEksJbYG9AYDa0oz9Ia10cIX6DQVBo1bexpcM62p7yvjVQV4Ivgyuu2ZIwVS8HtHSAkkgodg7w6UM46HBxrvnnTGgOpgDvxpJMNeCEYNhJjhho9d4QA/ViK/eUFAhuyOWy8bxftvCOxoA7C4VJYeGxLA7fs7kxcg556UK9dq2gAEF1XWHSwJRj9AusMvoNBlMic3Rlw3MP8YegMD9sMOuP67jsWV6HI/zGn5a+W02BwCbx5ujYyVQbJb/dmFlVYLgsNtrgDybFE2MyFZ9VGF4c+0WxWfmDUx4IA6nAK8fbStCb3GAmhUG+N1AmKj5lo4tx/TgiI9JIL5hVxjs2W8i6T6JUgiXCl5qLEzFY09QQ2AN2O6hcUWstdBIvlIB5QkJPKB+bWE+Ic7JpRH9WrVO1B8pHs1cKhxRUi/4D6PVph0W506r28ly75yr+pls5V274IEOo/XI54QwzKtbyzBlT+OJ6r69RmB5IDhC2BskoqNlKwRCOjODsh7+1Ztld+T2pUmZiK3hNTBUuZjMvjI/53Z3H0fP7Ec9QJIN5M0r2wdZ25EP4GT7caB7bdAnDe152m5eex+2qwS5jJy8CkCbjUcA++ifvnKouVrH5kyq1OoOrIUDPqU11MEpTCDvsLOpjOpkzE84UL+LT4=
    user: AgA7+wCOT1nuVVuX0zVaXGvjlTIPWvJfwMNkymTRv6LhjGh4nZ5lcHltT8EbywZkdZeUBKbgJmOi9puI035SWZMSW01lnM+8kTPBjHHQMJON6L9T99zT6hNalLvFBUGTd7wm8865F0qI3ImjQIDXJ2nXnWMbBBUYaltMaD337VSBDotePXli1sl5jYGW5tVClwiu4h430Ry3qkzY+5BbMWqp5G4tdavHMdlD+Ml/abzi86Ixi2M8/T+Ys/gYXhQIrfgJu0wQC/8H3Eo/5/AeVelAtBpYD3W0cbevexvYKUYOGoPKGOsW3rYYGXy0AYbFwg+VwTbEd4eJ3WWW1nKSoHQdsYLVWusfQTaH6Izs+BfTjqlxcFmAkPxQZRcIoj4hSYzzT7d1CiymhUDwp+29b5GCi2jXYkMy3F9inv2AC0px5oC1IdwMqdt4we1HqBnK465GqHHIHvrkeVu5yu859XsFieqjXAWgK4Cofr/L/aFtiizpLeQreO9hcZNEwtIzIKevkVp1r3u5yTPepjL3U8TKairsJueT6J91CrHUSh7TTXgpGJC199dUcuSDENDAUEapKWtnYyDux9MJvjMiIq50jQKemXQYdYV/5lX6NLQFnMY1R7oKXVF6SxgOK20IU8O/NuJS4GG2LIrDi5viBuEjl9v51fyiIZiGRd1I4H3VG7mrrNuOg/GxXmtWg7b27CVzGYwzkQ==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: basic-auth           
      namespace: default
