apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: basic-auth
  namespace: default
spec:
  encryptedData:
    password: AgAkDkVQkyDYJ6cjwCyEF0IT3Fg3D926sZyC6aHNENuuO0SM2xhgrvl4rUC6L5ASqpa107mmHuxu5NIV8pm9+CTitjExhA4ZVOp2yrwP8m+rAIH16iPBhPl7lHFSjwe29qE1zkkxovKm8Si4Rw+kmW8TsuE0PhQNLyUj7fyOOvifBV5a69dpP9GGYIODuafWlcslGZBWNsYYzOa5XkWdRpUTMRNKh3pyazndun4RlMUur+Wlie903S+F4rnCdShhCiZgbc8XVRu7qOYkU0AI8esku5qrU4icZDEUkJJzSfo/A8RfUxXjeoVZQzfsBur6rsl1BhLMQG9YCU85dTzx9JtzQjsJoTs/E4hpbR++xbJk3IB4sp+o6xPyWv3iILZJQaYn1Gk3VBV6cJlnfduBPTr4GOa66t/2KPAUr5BETkCj9kHVvbQo5TJJRAB9jEUq3aRmOSUtUE0WdEXm58B17ocK/2j21vZNID/sFKox9lmv8zY5DTE1fTlgj62AAD8FrDCLGuRPwMPbwGRfr0HrXQWqjSSSX6xT6dy0gAVJW7VMBFFQTW13ZHFgD2RFxo01nWUCxDjA6004wdhNNu9i+8wbJBhKOzjqa3lposQwf1mVuOwsVmPfYvsU0qEVpDFMLS4HItHjLVimv3RKxTK/6AlC9ul4YgAD4HFD0YkkrfiXHu7UMsEnCMUKz2/FebTTNyY=
    user: AgAoGNt8ZYt7OmwHxikQ5HmN1Junu7M5Rp7W/Zim3Aky6g/YC+HUuVJkeJ4z4sZE3YoQyaYLEGdFtfib7QOwP0RJFI36v/XvMykdgkvigMVA83BkcPtdeMgpeqnT4jj7opIC854096x5m4bde0PdBvZvFYItkwLNetOJ1FxWyybBH+hY5v0aoPn8kr9GtNPI/+nUCMNPqxMYEHENH6c+g/vJxlCFve7tG903d3su+j94DwpcdFMUEs69Fr2qHCcqZgpQ5+n898ydD4/eqTT6DZOD1DL4nSB5rIiM7ias6B8X2QYtn3RvbCaGE70vM0PCvPV3IXpC8P7I01IZxLBTr45Ztkt9z5mY45gqX3upxA3Zx5JkhZ8H9E5XNp2AF5UVFCkFj5chjAexRMEqS/1rKR8nuUm9qr58dV3I6MdVzuAx/htf8Cqw++Z/nrTM7exzruUMVzTriMmG6wlImenFnuKSQdDQisUfavFdXxFi21FXr1N1u+qi0GTAmVqd8RwZPjdgTB7+Hzei/eLg/2ykZcOLxY9VMq0zneucOS4nA5hOXhaHpW1rKN4hlANXwIps3a7v4vVgL/w7B4V4h779k9HGvOjBLDfH7gTBDrKUEWTSJtQe7fnWFVq9KmZ0fBrZpQt//918SLWOl634i4RJ0U6f9c5dDT1l3YXlsJ5oXCXP+5Xllz6UoWLUgRD7qM2Bi7A=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: basic-auth
      namespace: default



